In [19]:
    import numpy as np

    import tensorflow as tf


    # 使用占位符从python向TensorFlow运算符中传递参数值。我们在这里定义了两个占位符，其中一个用来存放输入特征x，另一个用来存放输出y.

    x = tf.placeholder(tf.float32)

    y = tf.placeholder(tf.float32)


    # 假设我们已经知道了期望的函数是一个二次多项式，我们就会分配一个具有3个元素的向量来代表这些参数。这些变量会被以随机地进行初始化。

    w = tf.Variable(tf.zeros([3, 1]))

    # 我们定义yhat为我们对y的估计值

    f = tf.stack([tf.square(x), x, tf.ones_like(x)], 1)

    yhat = tf.squeeze(tf.matmul(f, w))

    # 损失函数被定义为y的估计值和真实值之间地l2距离。我们还附加了一个收缩项，以确保结果得到的权值会比较小。

    loss = tf.nn.l2_loss(yhat - y) + 0.1 * tf.nn.l2_loss(w)

    # 我们以0.1的学习率使用Adam优化器来最小化损失函数。

    train_op = tf.train.AdamOptimizer(0.1).minimize(loss)

    def generate_data():

        x_val = np.random.uniform(-10.0, 10.0, size=100)

        y_val = 5 * np.square(x_val) + 3

        return x_val, y_val


    sess = tf.Session()

    # 因为我们要使用这些变量，所以我们需要先将它们初始化

    sess.run(tf.global_variables_initializer())

    for _ in range(1000):

        x_val, y_val = generate_data()

        _, loss_val = sess.run([train_op, loss], {x: x_val, y: y_val})

        print(loss_val)

        print(sess.run([w]))

    

2.66475e+06
[array([[ 0.1],
       [ 0.1],
       [ 0.1]], dtype=float32)]
2.18673e+06
[array([[ 0.19914746],
       [ 0.05671668],
       [ 0.19936842]], dtype=float32)]
1.84464e+06
[array([[ 0.29713535],
       [ 0.09894345],
       [ 0.29779726]], dtype=float32)]
2.51121e+06
[array([[ 0.39617446],
       [ 0.16652243],
       [ 0.39697552]], dtype=float32)]
2.00609e+06
[array([[ 0.49497154],
       [ 0.22249722],
       [ 0.49585345]], dtype=float32)]
1.98193e+06
[array([[ 0.59367979],
       [ 0.25038445],
       [ 0.59468687]], dtype=float32)]
1.88685e+06
[array([[ 0.6921885 ],
       [ 0.25215656],
       [ 0.69337052]], dtype=float32)]
2.10692e+06
[array([[ 0.79126537],
       [ 0.25072017],
       [ 0.79230005]], dtype=float32)]
1.91241e+06
[array([[ 0.89038014],
       [ 0.22861409],
       [ 0.89114463]], dtype=float32)]
1.64047e+06
[array([[ 0.98880959],
       [ 0.22712976],
       [ 0.98925519]], dtype=float32)]
1.2168e+06
[array([[ 1.08505654],
       [ 0.21639791],
     

92.4445
[array([[ 4.97668695],
       [-0.01131047],
       [ 4.87983751]], dtype=float32)]
80.9697
[array([[ 4.97574043],
       [-0.01021243],
       [ 4.87751579]], dtype=float32)]
89.5656
[array([[ 4.97484064],
       [-0.0091729 ],
       [ 4.87522936]], dtype=float32)]
75.5103
[array([[ 4.97398806],
       [-0.00812925],
       [ 4.87300205]], dtype=float32)]
77.7138
[array([[ 4.97319603],
       [-0.00713558],
       [ 4.87083769]], dtype=float32)]
91.5116
[array([[ 4.97244549],
       [-0.00620016],
       [ 4.8686924 ]], dtype=float32)]
74.7666
[array([[ 4.97174644],
       [-0.00532779],
       [ 4.8666048 ]], dtype=float32)]
84.4276
[array([[  4.97109461e+00],
       [ -4.65407968e-03],
       [  4.86455107e+00]], dtype=float32)]
88.3766
[array([[  4.97047853e+00],
       [ -4.08944488e-03],
       [  4.86251354e+00]], dtype=float32)]
86.9699
[array([[  4.96991205e+00],
       [ -3.50153819e-03],
       [  4.86050844e+00]], dtype=float32)]
74.7855
[array([[  4.96938610e+00],

70.183
[array([[  4.97099829e+00],
       [ -2.32094899e-03],
       [  4.74244833e+00]], dtype=float32)]
67.8752
[array([[  4.97100878e+00],
       [ -2.35890457e-03],
       [  4.74079275e+00]], dtype=float32)]
71.5229
[array([[  4.97101307e+00],
       [ -2.28494592e-03],
       [  4.73912001e+00]], dtype=float32)]
71.1235
[array([[  4.97104788e+00],
       [ -2.14889762e-03],
       [  4.73746872e+00]], dtype=float32)]
70.3228
[array([[  4.97107077e+00],
       [ -1.96754630e-03],
       [  4.73579836e+00]], dtype=float32)]
68.6027
[array([[  4.97106504e+00],
       [ -1.80463248e-03],
       [  4.73409748e+00]], dtype=float32)]
72.7946
[array([[  4.97106647e+00],
       [ -1.64237933e-03],
       [  4.73238993e+00]], dtype=float32)]
72.8067
[array([[  4.97107983e+00],
       [ -1.59823766e-03],
       [  4.73068142e+00]], dtype=float32)]
64.2326
[array([[  4.97109509e+00],
       [ -1.54848024e-03],
       [  4.72898436e+00]], dtype=float32)]
65.8146
[array([[  4.97109890e+00],
  

54.1461
[array([[  4.97360468e+00],
       [ -2.11606763e-04],
       [  4.54433727e+00]], dtype=float32)]
61.0209
[array([[  4.97367382e+00],
       [ -1.56585884e-04],
       [  4.54249001e+00]], dtype=float32)]
52.525
[array([[  4.97373486e+00],
       [ -1.31452893e-04],
       [  4.54064274e+00]], dtype=float32)]
58.0264
[array([[  4.97379303e+00],
       [  8.97116843e-06],
       [  4.53877974e+00]], dtype=float32)]
58.4721
[array([[  4.97382641e+00],
       [  1.76252597e-05],
       [  4.53687811e+00]], dtype=float32)]
55.3964
[array([[  4.97386885e+00],
       [  1.54485788e-05],
       [  4.53498363e+00]], dtype=float32)]
64.6304
[array([[  4.97390747e+00],
       [ -5.28234195e-05],
       [  4.53305006e+00]], dtype=float32)]
48.9181
[array([[  4.97395325e+00],
       [ -2.30396152e-04],
       [  4.53114748e+00]], dtype=float32)]
55.9309
[array([[  4.97400904e+00],
       [ -3.95431533e-04],
       [  4.52925062e+00]], dtype=float32)]
50.7534
[array([[  4.97405386e+00],
  

       [  4.08662558e+00]], dtype=float32)]
29.9766
[array([[  4.98152876e+00],
       [  1.25520851e-03],
       [  4.08476400e+00]], dtype=float32)]
28.8377
[array([[  4.98157549e+00],
       [  1.25507731e-03],
       [  4.08291340e+00]], dtype=float32)]
27.4224
[array([[  4.98160839e+00],
       [  1.30698353e-03],
       [  4.08105469e+00]], dtype=float32)]
29.1136
[array([[  4.98163176e+00],
       [  1.47439912e-03],
       [  4.07917833e+00]], dtype=float32)]
30.7667
[array([[  4.98166895e+00],
       [  1.61962281e-03],
       [  4.07729721e+00]], dtype=float32)]
30.7241
[array([[  4.98169899e+00],
       [  1.71332760e-03],
       [  4.07539129e+00]], dtype=float32)]
28.9494
[array([[  4.98173189e+00],
       [  1.74349570e-03],
       [  4.07348537e+00]], dtype=float32)]
28.6869
[array([[  4.98176003e+00],
       [  1.65347860e-03],
       [  4.07157278e+00]], dtype=float32)]
29.0896
[array([[  4.98178816e+00],
       [  1.53971603e-03],
       [  4.06965494e+00]], dtype=flo

19.5084
[array([[  4.98475838e+00],
       [ -1.02724612e-03],
       [  3.90846252e+00]], dtype=float32)]
20.1002
[array([[  4.98480082e+00],
       [ -1.13267801e-03],
       [  3.90668702e+00]], dtype=float32)]
20.1621
[array([[  4.98483753e+00],
       [ -1.16039463e-03],
       [  3.90491271e+00]], dtype=float32)]
21.2721
[array([[  4.98486376e+00],
       [ -1.30315090e-03],
       [  3.90312314e+00]], dtype=float32)]
20.2461
[array([[  4.98487902e+00],
       [ -1.54394843e-03],
       [  3.90132689e+00]], dtype=float32)]
21.0442
[array([[  4.98487902e+00],
       [ -1.68636045e-03],
       [  3.89951158e+00]], dtype=float32)]
22.0986
[array([[  4.98488045e+00],
       [ -1.77858863e-03],
       [  3.89768362e+00]], dtype=float32)]
19.3458
[array([[  4.98489046e+00],
       [ -1.73612894e-03],
       [  3.89587808e+00]], dtype=float32)]
20.3791
[array([[  4.98489237e+00],
       [ -1.70619227e-03],
       [  3.89406538e+00]], dtype=float32)]
20.8971
[array([[  4.98488951e+00],
 

11.8641
[array([[  4.98849249e+00],
       [ -1.24584956e-04],
       [  3.67287660e+00]], dtype=float32)]
11.8884
[array([[  4.98857212e+00],
       [ -2.14973756e-04],
       [  3.67142081e+00]], dtype=float32)]
12.9919
[array([[  4.98864841e+00],
       [ -2.15399996e-04],
       [  3.66995025e+00]], dtype=float32)]
11.1495
[array([[  4.98874760e+00],
       [ -2.16049622e-04],
       [  3.66851854e+00]], dtype=float32)]
12.0222
[array([[  4.98882246e+00],
       [ -3.11627198e-04],
       [  3.66706395e+00]], dtype=float32)]
11.7971
[array([[  4.98889399e+00],
       [ -3.92836053e-04],
       [  3.66560960e+00]], dtype=float32)]
13.0037
[array([[  4.98896074e+00],
       [ -5.26296149e-04],
       [  3.66413546e+00]], dtype=float32)]
11.6352
[array([[  4.98903513e+00],
       [ -6.03394641e-04],
       [  3.66267586e+00]], dtype=float32)]
12.92
[array([[  4.98910713e+00],
       [ -6.64611405e-04],
       [  3.66119957e+00]], dtype=float32)]
12.2014
[array([[  4.98917627e+00],
   

       [  3.55686855e+00]], dtype=float32)]
8.13263
[array([[  4.99069118e+00],
       [ -2.11255960e-04],
       [  3.55560708e+00]], dtype=float32)]
8.13339
[array([[  4.99073792e+00],
       [ -1.77239388e-04],
       [  3.55434656e+00]], dtype=float32)]
8.50187
[array([[  4.99077940e+00],
       [ -1.66115075e-04],
       [  3.55308223e+00]], dtype=float32)]
9.47109
[array([[  4.99080753e+00],
       [ -1.94450797e-04],
       [  3.55178738e+00]], dtype=float32)]
8.07561
[array([[  4.99083567e+00],
       [ -2.22249000e-04],
       [  3.55050302e+00]], dtype=float32)]
8.52404
[array([[  4.99087954e+00],
       [ -2.70529592e-04],
       [  3.54923463e+00]], dtype=float32)]
8.61324
[array([[  4.99093103e+00],
       [ -2.82800233e-04],
       [  3.54797220e+00]], dtype=float32)]
8.53253
[array([[  4.99096918e+00],
       [ -3.41443025e-04],
       [  3.54669619e+00]], dtype=float32)]
8.34103
[array([[  4.99100399e+00],
       [ -4.62938391e-04],
       [  3.54541945e+00]], dtype=flo

6.22695
[array([[  4.99231672e+00],
       [  2.61967699e-03],
       [  3.44550514e+00]], dtype=float32)]
6.10288
[array([[  4.99230242e+00],
       [  2.63664685e-03],
       [  3.44434500e+00]], dtype=float32)]
6.24952
[array([[  4.99229527e+00],
       [  2.63087335e-03],
       [  3.44319153e+00]], dtype=float32)]
7.16662
[array([[  4.99229050e+00],
       [  2.60977773e-03],
       [  3.44201612e+00]], dtype=float32)]
6.01882
[array([[  4.99229813e+00],
       [  2.47763284e-03],
       [  3.44086075e+00]], dtype=float32)]
6.14045
[array([[  4.99231100e+00],
       [  2.30777659e-03],
       [  3.43971372e+00]], dtype=float32)]
6.2854
[array([[  4.99233770e+00],
       [  2.05730856e-03],
       [  3.43857980e+00]], dtype=float32)]
6.29174
[array([[  4.99237108e+00],
       [  1.80130021e-03],
       [  3.43745065e+00]], dtype=float32)]
5.96198
[array([[  4.99241447e+00],
       [  1.50457688e-03],
       [  3.43633819e+00]], dtype=float32)]
6.04581
[array([[  4.99245691e+00],
  

In [32]:
import tensorflow as tf  
  
a = tf.constant([1,2,3,31])  
b = tf.constant([4,5,6,61])
b2 = tf.constant([7,8,9,91])
  
c = tf.stack([a,b,b2],axis=0)  
d = tf.stack([a,b,b2],axis=1)

  
e = tf.unstack(d,axis=0)  
f = tf.unstack(d,axis=1)  
  
  
with tf.Session() as sess:  
    print('原始向量数据：')  
    print(sess.run(a))  
    print(sess.run(b))       
    print('矩阵拼接的函数示例,得到一个矩阵：')  #返回值是多维矩阵  
    print('以"0维"的方式进行拼接')  
    print(sess.run(c))  
    print('以"1维"的方式进行拼接')  
    print(sess.run(d))  
      
    print('矩阵分解的函数示例，得到一个list：') #返回值是一个list     
    print('以"0维"的方式进行分解')  
    print(sess.run(e))  
    print('以"1维"的方式进行分解')  
    print(sess.run(f)) 

原始向量数据：
[ 1  2  3 31]
[ 4  5  6 61]
矩阵拼接的函数示例,得到一个矩阵：
以"0维"的方式进行拼接
[[ 1  2  3 31]
 [ 4  5  6 61]
 [ 7  8  9 91]]
以"1维"的方式进行拼接
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [31 61 91]]
矩阵分解的函数示例，得到一个list：
以"0维"的方式进行分解
[array([1, 4, 7], dtype=int32), array([2, 5, 8], dtype=int32), array([3, 6, 9], dtype=int32), array([31, 61, 91], dtype=int32)]
以"1维"的方式进行分解
[array([ 1,  2,  3, 31], dtype=int32), array([ 4,  5,  6, 61], dtype=int32), array([ 7,  8,  9, 91], dtype=int32)]


In [30]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
tf.concat([t1, t2], 0)
with tf.Session() as sess:  
    print(sess.run(tf)) 

TypeError: Fetch argument <module 'tensorflow' from '/home/mok/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/__init__.py'> has invalid type <class 'module'>, must be a string or Tensor. (Can not convert a module into a Tensor or Operation.)